"""Create database

Revision ID: 54dfc5eb25d
Revises: None
Create Date: 2015-02-22 15:30:31.663349

"""

# revision identifiers, used by Alembic.
revision = '54dfc5eb25d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic ###
    op.create_table('user',
    sa.Column('idn', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('idn')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_nickname'), 'user', ['nickname'], unique=True)
    op.create_table('student',
    sa.Column('idn', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=140), nullable=True),
    sa.Column('last_name', sa.String(length=140), nullable=True),
    sa.Column('email', sa.String(length=140), nullable=True),
    sa.Column('id_card_number', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('idn'),
    sa.UniqueConstraint('id_card_number')
    )
    op.create_table('event',
    sa.Column('idn', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('idn')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic ###
    op.drop_table('event')
    op.drop_table('student')
    op.drop_index(op.f('ix_user_nickname'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    ### end Alembic commands ###
